### PR TITLE
Fixing segfault

### PR DESCRIPTION
**Pull request by hey-adora**
I'm not sure how no one noticed it (probably because the original repository is nowhere to be found?), but it segfaults on launch, even package from AUR segfaults.

```
/home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui
Connection manager: Network Manager >= 0.9.0
Modem manager: Modem Manager >= 0.7.0
Segmentation fault at address: 0x55f58b9efe0b
Stack trace:
1. /usr/lib/libc.so.6(+0x15a72b) [0x7febf82f972b]
2. /usr/lib/libc.so.6(+0x15a72b) [0x7febf82f972b]
3. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(mmgui_notifications_new+0x3ab) [0x55f0d347432e]
4. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(+0x5ecf9) [0x55f0d34b9cf9]
5. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(+0x56b2c) [0x55f0d34b1b2c]
6. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(+0x2d88e) [0x55f0d348888e]
7. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(mmgui_svcmanager_start_services_activation+0x92) [0x55f0d3487cb0]
8. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(+0x2febe) [0x55f0d348aebe]
9. /home/night/Documents/github/modem-manager-gui-github/buildDir/src/modem-manager-gui(mmguicore_start+0x26) [0x55f0d348f862]

Process finished with exit code 1
```

looks like it just freed the memory too early. should be fixed now.
it still doesnt fix the problem of it not detecting any of my devices, but its a start lol.

### CODE REVIEW

**Comment by dmikushin** [comment]
@hey-adora , thanks for this ! Yes, I've picked up this project from nowhere, because I needed a modem and fixed a similar issue to yours. Yes, it's likely there are more of them :) Please keep hunting, and let's make modem-manager-gui great again! :+1:

**Comment by dmikushin** [comment]
@hey-adora I can confirm it works for me on Ubuntu 22.04. Are you able to get to the main screen below ?

Screenshot from 2024-01-31 21-04-20

**Comment by hey-adora** [comment]
@dmikushin it works now, but it says "No devices found in system" im not sure why. I bought a HUAWEI E3531 usb modem. Not sure if im missing some packages or something. it said it would work on linux on the online shop where i bought it from.
But ye, im not sure how great we can make it lol.

(also, did it work for you before? this segfault must be only for specific to some library versions maybe (im on latest arch))

image

**Comment by dmikushin** [comment]
@hey-adora With Chinese USB modem I think you are taking a wrong path. In my experience, what they do is more similar to a home router box, but plugged into the USB. When plugged, you should see that the dongle creates a network interface in `ifconfig`. It's basically a usbeth (USB Tethering). And then you call up the dongle's home page with an IP address 192.168.1.1 or whatever they define on their sticker. Then you do the rest of config on this embedded web site via your browser. That's all, very simple, try it!

My use case for modem-manager-gui is a lot different. I need to talk to a a bare metal modem card, which is only able to send AT commands over the USB-CDC lane. In fact, it's a real telephone modem thing on a serial cable. It ignores the most of USB capabilities and simply turns USB into a serial lane, like Arduino. We are lucky that Chinese are smart enough to avoid this nightmare in their designs. Overall, everything that connects via USB is much more pleasant.

So strictly speaking, HUAWEI E3531 is not a modem in the real (legacy) meaning of this word, as it is in my case. Your device in fact is a mobile hotspot. They should not be called modems to avoid misunderstanding of the required software stack.

**Comment by hey-adora** [comment]
@dmikushin i see lol, thanks for the clarification. And ye i already tried connecting to it prior to this and failed also read all of the manuals for it.
i can see it using `lsusb`, 
`Bus 003 Device 007: ID 12d1:15ca Huawei Technologies Co., Ltd. E3131 3G/UMTS/HSPA+ Modem (Mass Storage Mode)`
(i wonder if this "Mass Storage Mode" means i have to switch it to a different mode somehow lol)
but cant see anything new with `ip a` or `ip r` or `nmcli`. But no worries, ill solve it, i dont want to make this pull request into a Huawei support channel lol.
(note, `ip a` is replacement for `ifconfig`)

Also, should i make some build script for making this into an appimage? or release it on flathub? would be a shame to just leave it here for people to compile it manually lol, this is the only working version for me.

**Comment by dmikushin** [comment]
> Also, should i make some build script for making this into an appimage? or release it on flathub? would be a shame to just leave it here for people to compile it manually lol, this is the only working version for me.

Thank you for your kind words, please feel free to release it to AUR, which is a very good thing you Arch people have.

**Comment by dmikushin** [comment]
> i wonder if this "Mass Storage Mode" means i have to switch it to a different mode somehow lol

Check this:

```
►lsmod | grep usbnet
usbnet                 65536  3 cdc_mbim,cdc_ncm,cdc_ether
```

**Pull request merged**
